---
- name: Build image with Packer
  hosts: all
  vars:
    #
    # Base configuration
    #
    packer_binary: packer.io
    packer_builder: qemu
    packer_target: rhel_8_6
    image_name: packer_image.qcow2
    disk_size: 30720

    # Build options
    do_cleanup: true
    use_force: false

    #
    # OS configuration
    #
    boot_password: "{{ image_password }}"
    root_password: "{{ image_password }}"
    bios_uefi_boot: true
    # auto/custom/default/single
    partitioning: auto
    disable_ipv6: true
    selinux: enforcing
    #security_profile: cis_server_l1
    boot_parameters: net.ifnames.prefix=net quiet systemd.show_status=yes
    serial_console_setup: true

    hostname: localhost.localdomain
    ntp_servers: time.cloudflare.com
    timezone: Europe/Helsinki
    keyboard: fi

    create_admin: true
    admin_user:
      uid: 4444
      gid: 4444
      name: admin
      group: admin
      groups: wheel
      home: /home/admin
      gecos: Admin User
      #ssh_key: "ssh-rsa ... admin@image"
      passwordless_sudo: true

    root_permit_local: true
    root_permit_ssh: "prohibit-password"
    root_permit_override_security_policy: false
    #root_ssh_key: "ssh-rsa ... root@image"

    #custom_partitioning: |
    #  reqpart
    #  part /boot    --fstype xfs      --size 1024 --grow
    #  part /        --fstype xfs      --size 1024 --grow
    #  part swap     --fstype swap     --size 2048

    #custom_packages: |
    #  cloud-init
    #  cloud-utils-growpart
    #  insights-client
    #  rhc
    #  rhc-worker-playbook
    #  sos
    #  unzip
    #  zsh

    #custom_section_early: |
    #  %post --erroronfail
    #  cat /etc/resolv.conf > /var/tmp/.inst-resolv-conf
    #  %end

    #custom_section_late: |
    #  %post --erroronfail
    #  touch /.unconfigured
    #  %end

    #
    # Builder configurations
    #

    # Builder: qemu
    # https://www.packer.io/docs/builders/qemu
    qemu_binary: /usr/libexec/qemu-kvm
    output_directory: /tmp/packer_images

    # Builder: vmware
    # https://www.packer.io/docs/builders/vsphere/vsphere-iso
    #vcenter_credentials:
    #  vcenter_server: vcenter.example.com
    #  vcenter_username: vcuser
    #  vcenter_password: vcpass
    vcenter_insecure_connection: true
    vcenter_datacenter: DC1
    vcenter_folder: Linux/templates
    # https://www.packer.io/docs/builders/vsphere/vsphere-iso#working-with-clusters-and-hosts
    #vcenter_host: vcenter-host1.example.com
    vcenter_cluster: DC1-C1
    #vcenter_resource_pool: DC1-RP1
    vcenter_datastore: DC1-C1-LUN-1
    vcenter_network: DC1-C1-VLAN-123
    #vm_guest_os_type: rhel8_64Guest
    #vm_firmware: bios
    # https://www.packer.io/plugins/builders/vsphere/vsphere-iso#content-library-import-configuration
    vcenter_convert_to_template: true
    #vcenter_content_library:
    #  library: DC1-CL
    #  #name: cl-template
    #  ovf: false
    #  destroy: true

    #
    # OS installer configuration
    #
    iso:
      rhel_8:
        url: file:///VirtualMachines/boot/rhel-8.6-x86_64-dvd.iso
        checksum: sha256:c324f3b07283f9393168f0a4ad2167ebbf7e4699d65c9670e0d9e58ba4e2a9a8
      rhel_8_4:
        url: file:///VirtualMachines/boot/rhel-8.4-x86_64-dvd.iso
        checksum: sha256:48f955712454c32718dcde858dea5aca574376a1d7a4b0ed6908ac0b85597811
      rhel_8_5:
        url: file:///VirtualMachines/boot/rhel-8.5-x86_64-dvd.iso
        checksum: sha256:1f78e705cd1d8897a05afa060f77d81ed81ac141c2465d4763c0382aa96cadd0
      rhel_8_6:
        url: file:///VirtualMachines/boot/rhel-8.6-x86_64-dvd.iso
        checksum: sha256:c324f3b07283f9393168f0a4ad2167ebbf7e4699d65c9670e0d9e58ba4e2a9a8
      rhel_9:
        url: file:///VirtualMachines/boot/rhel-baseos-9.0-x86_64-dvd.iso
        checksum: sha256:a387f3230acf87ee38707ee90d3c88f44d7bf579e6325492f562f0f1f9449e89
      rhel_9_0:
        url: file:///VirtualMachines/boot/rhel-baseos-9.0-x86_64-dvd.iso
        checksum: sha256:a387f3230acf87ee38707ee90d3c88f44d7bf579e6325492f562f0f1f9449e89

    # boot_command will be appended by ' {{ boot_parameters }}<enter><wait>'
    boot_command: <up><wait><tab><wait> ip=dhcp inst.ks=hd:/dev/sr1:inst.cfg inst.geoloc=0 inst.nosave=all

  roles:
    - ansible-packer
