---
- name: Abort if not supported OS ISO URL
  fail:
    msg: "Custom ISO building requires file:// URL, aborting!"
  when: "'file://' not in iso[packer_target].url"

- name: Set OS ISO path
  set_fact:
    os_iso_path: "{{ iso[packer_target].url | regex_replace('^file://', '') }}"

- name: Set custom ISO full path
  set_fact:
    image_path: "{{ output_directory + '/' + image_name | default(target_fullname + '.iso', true) }}"

- name: Check existing custom ISO file
  stat:
    path: "{{ image_path }}"
  register: iso_image

- name: Abort if custom ISO file exists and not allowed to overwrite
  fail:
    msg: Custom ISO file already exists and use_force not enabled.
  when: not use_force | bool and iso_image.stat.exists

- name: Create output directory
  file:
    path: "{{ output_directory }}"
    state: directory

- name: Create custom ISO build directory
  file:
    path: "{{ tempdir.path + '/iso-build' }}"
    state: directory
  register: iso_build_dir

- name: Copy OS ISO files to custom ISO build directory
  command: 7z x -o{{ iso_build_dir.path }} {{ os_iso_path }}

- name: Create custom ISO boot loader files
  template:
    src: templates/{{ item.src }}
    dest: "{{ iso_build_dir.path + '/' + item.dest }}"
    mode: '0644'
  loop:
    - { 'src': 'grub.efi.j2', 'dest': 'EFI/BOOT/grub.cfg' }
    - { 'src': 'grub.iso.j2', 'dest': 'isolinux/grub.conf' }
    - { 'src': 'isolinux.cfg.j2', 'dest': 'isolinux/isolinux.cfg' }
  loop_control:
    label: "{{ item.dest }}"

- name: Copy installer configuration
  copy:
    src: "{{ tempdir.path + '/inst.cfg' }}"
    dest: "{{ iso_build_dir.path + '/inst.cfg' }}"
    mode: '0600'

- name: Remove existing custom ISO file
  file:
    path: "{{ image_path }}"
    state: absent
  when: use_force | bool and iso_image.stat.exists

- name: Build custom ISO file
  command:
    cmd: >
      genisoimage
      -b isolinux/isolinux.bin
      -c isolinux/boot.cat
      -no-emul-boot
      -boot-info-table
      -boot-load-size 4
      -eltorito-alt-boot
      -e images/efiboot.img
      -no-emul-boot
      -input-charset UTF-8
      -J -joliet-long -l -r -T
      -V {{ iso_volume_id }}
      -o {{ image_path }} .
    chdir: "{{ iso_build_dir.path }}"

- name: Make custom ISO hybrid bootable
  command: isohybrid --uefi {{ image_path }}

- name: Implant MD5 checksum into custom ISO
  command: implantisomd5 {{ image_path }}

- name: Calculate custom ISO SHA256 checksum
  command: sha256sum {{ image_path }}
  register: sha256sum_result

- name: Write SHA256 checksum to image checksum file
  copy:
    content: "{{ sha256sum_result.stdout + '\n' }}"
    dest: "{{ output_directory + '/' + image_checksum_file }}"
    mode: '0644'
