---
- name: Create Packer build file
  template:
    src: templates/build-{{ packer_builder }}.json.j2
    dest: "{{ tempdir.path }}/build.json"
    mode: '0600'

- name: Run Packer to build target image
  environment:
    PACKER_LOG: 1
    CHECKPOINT_DISABLE: 1
    TMPDIR: "{{ tempdir.path }}"
    VCENTER_PASSWORD: "{{ vcenter_credentials.vcenter_password | default(omit) }}"
  command:
    cmd: "{{ packer_binary }} build -color=false {{ '-force' if use_force | bool else '' }} build.json"
    chdir: "{{ tempdir.path }}"
  register: packer_result
  failed_when: "'successful build' not in packer_result.stdout"

- name: Display Packer command output
  debug:
    var: packer_result.stdout
